---
name: "Release GAP package"
description: "Makes a release of the GAP package on GitHub, with archives and manuals as assets"
inputs:
  dry-run:
    description: "Set to true to not push the release to GitHub"
    required: false
    default: "false"

runs:
  using: "composite"
  steps:
    - name: "Validate PackageInfo.g"
      shell: bash
      run: |
        gap -A -q -c 'QuitGap(ValidatePackageInfo("PackageInfo.g"));'

    - name: "Create assets folder"
      shell: bash
      run: |
        ASSETS=$RUNNER_TEMP/assets
        mkdir -p $ASSETS
        echo "ASSETS=$ASSETS" | tee -a "$GITHUB_ENV"

    - name: "Generate package-info.json"
      shell: bash
      run: |
        gap -A -q $GITHUB_ACTION_PATH/pkginfo_to_json.g
        if [ ! -f "package-info.json" ] ; then
            echo "Could not create package-info.json"
            exit 1
        fi
        mv package-info.json $ASSETS
        
    - name: "Read data from package-info.json"
      shell: bash
      working-directory: ${{ env.ASSETS }}
      run: |
        TMP=($(cat package-info.json | jq -r '.ArchiveURL' | tr "/" " "))
        if [ "${#TMP[@]}" -eq 8 ] &&
           [ "${TMP[0]}" = "https:" ] &&
           [ "${TMP[1]}" = "github.com" ] &&
           [ "${TMP[4]}" = "releases" ] &&
           [ "${TMP[5]}" = "download" ]; then
            echo "TAG=${TMP[6]}" | tee -a "$GITHUB_ENV"
            echo "BASENAME=${TMP[7]}" | tee -a "$GITHUB_ENV"
        else
            echo "ArchiveURL in PackageInfo.g does not point to a GitHub release"
            exit 1
        fi
        echo "PKGNAME=$(cat package-info.json | jq -r '.PackageName')" | tee -a "$GITHUB_ENV"
        echo "VERSION=$(cat package-info.json | jq -r '.Version')" | tee -a "$GITHUB_ENV"
        echo "ARCHIVE_FORMATS=$(cat package-info.json | jq -r '.ArchiveFormats' | tr "," " ")" | tee -a "$GITHUB_ENV"
        echo "DOCS=$(cat package-info.json | jq -r '.PackageDoc[].PDFFile' | tr "\n" " ")" | tee -a "$GITHUB_ENV"

        case "$VERSION" in
          *dev)
            echo "Must not use 'dev' versions for package releases"
            exit 1
            ;;
        esac

    # We make a copy of the current directory to build the release from, because
    # the next step will remove files/folders that may be necessary for subsequent
    # actions
    - name: "Make copy of package"
      shell: bash
      run: |
        mkdir -p "$RUNNER_TEMP/$BASENAME"
        cp -r * "$RUNNER_TEMP/$BASENAME"
        
    - name: "Cleanup before making archives"
      shell: bash
      working-directory: ${{ runner.temp }}/${{ env.BASENAME }}
      run: | 
         echo "::group:: Cleanup git and github related files"
         rm -rvf .git* .hg* .cvs* .circleci
         echo "::group:: Cleanup codecov, travis, azure-pipelines"
         rm -fv .codecov.* .travis.* .appveyor.* azure-pipelines.*
         rm -fv .gaplint.*
         rm -fv requirements.txt

         echo "::group:: Cleanup macOS metadata"
         find . -name .DS_Store -exec rm -f {} +

    - name: "Run autogen.sh"
      shell: bash
      working-directory: ${{ runner.temp }}/${{ env.BASENAME }}
      if: ${{ inputs.release-script != '' }}
      run : |
        if [ -x autogen.sh ] ; then
          sudo apt-get install autoconf automake build-essential --yes
          echo "Generating build system files"
          sh autogen.sh
          rm -rf autom4te.cache
        fi
        
    - name: "Create archives"
      shell: bash
      working-directory: ${{ runner.temp }}
      run: |
        for EXT in $ARCHIVE_FORMATS ; do
            ARCHIVENAME=$BASENAME$EXT
            echo "Creating $ARCHIVENAME ..."
            case $EXT in
            .tar.gz)  tar cf - "$BASENAME" | gzip -9c > "$ASSETS/$ARCHIVENAME" ;;
            .tar.bz2) tar cf - "$BASENAME" | bzip2 -9c > "$ASSETS/$ARCHIVENAME" ;;
            .zip)     zip -r9 --quiet "$ASSETS/$ARCHIVENAME" "$BASENAME" ;;
            *)
                echo "Unsupported archive format $EXT"
                exit 1
                ;;
            esac
            if [ ! -f "$ASSETS/$ARCHIVENAME" ] ; then
                echo "Failed at creating "$ARCHIVENAME""
                exit 1
            fi
            echo "Created $ARCHIVENAME"
        done

    - name: "Copy manual(s)"
      shell: bash
      run: |
        for DOC in $DOCS ; do
            cp $DOC $ASSETS
        done

    - name: "Make GitHub release"
      uses: softprops/action-gh-release@v2
      if: ${{ inputs.dry-run == 'false' }}
      with:
        body: "Release for ${{ env.PKGNAME }}"
        name: "${{ env.PKGNAME }} ${{ env.VERSION }}"
        fail_on_unmatched_files: true
        tag_name: "${{ env.TAG }}"
        files: ${{ env.ASSETS }}/*

    - name: "Upload the release"
      uses: actions/upload-artifact@v4
      if: ${{ inputs.dry-run == 'true' }}
      with:
        name: "Release_for_${{ env.PKGNAME }}_${{ env.VERSION }}"
        path: ${{ env.ASSETS }}/*
        if-no-files-found: error
