---
name: Continuous Integration for action
on:
  - pull_request
  - push

jobs:
  test:
    name: Test action
    runs-on: ubuntu-latest
    steps:
      # the order of the checkout actions is important because all contents of
      # the target folder of the checkout action is removed
      - uses: actions/checkout@v4
        with:
          repository: gap-packages/example

      - uses: actions/checkout@v4
        with:
          path: this-action/

      - name: gap -- setup
        uses: gap-actions/setup-gap@v2
        with:
          GAP_PKGS_TO_BUILD: json

      - name: gap -- build docs
        uses: gap-actions/build-pkg-docs@v1
        with:
          use-latex: true

      - uses: ./this-action/
        with:
          dry-run: true
